import type { Preset } from '../../../../../types';

export const daisyPresets: Preset[] = [
  // ==================== DAISY UI COMPLETE THEMES ====================
  {
    name: 'Daisy Default', baseColor: '#1E1E2F', temperature: 'natural', category: 'daisy',
    description: 'DaisyUI default theme',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Light', baseColor: '#FFFFFF', temperature: 'natural', category: 'daisy',
    description: 'Bright and airy',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Dark', baseColor: '#1F2937', temperature: 'cooler', category: 'daisy',
    description: 'Deep dark theme',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Cupcake', baseColor: '#FDF4FF', temperature: 'warmer', category: 'daisy',
    description: 'Sweet and playful',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Nunito',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'relaxed',
      letterSpacing: 'wide',
      buttonRadius: 'full', cardRadius: 'lg', inputRadius: 'full',
      shadow: 'md', density: 'spacious', borderWidth: '2',
    },
  },
  {
    name: 'Daisy Bumblebee', baseColor: '#FEF3C7', temperature: 'warmer', category: 'daisy',
    description: 'Bright yellow energy',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '2',
    },
  },
  {
    name: 'Daisy Emerald', baseColor: '#ECFDF5', temperature: 'cooler', category: 'daisy',
    description: 'Fresh green theme',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Corporate', baseColor: '#F9FAFB', temperature: 'cooler', category: 'daisy',
    description: 'Professional corporate',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: 'xl', fontSizeBody: 'sm', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'compact', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Synthwave', baseColor: '#2D1B69', temperature: 'cooler', category: 'daisy',
    description: 'Retro synthwave vibes',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'tight',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'xl', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Daisy Retro', baseColor: '#E4D5B7', temperature: 'warmer', category: 'daisy',
    description: 'Vintage retro style',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Cyberpunk', baseColor: '#0F172A', temperature: 'cooler', category: 'daisy',
    description: 'Neon cyberpunk theme',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'tight',
      buttonRadius: 'sm', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'lg', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Daisy Valentine', baseColor: '#FCE7F3', temperature: 'warmer', category: 'daisy',
    description: 'Romantic pink theme',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Nunito',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'lg', inputRadius: 'full',
      shadow: 'md', density: 'spacious', borderWidth: '2',
    },
  },
  {
    name: 'Daisy Halloween', baseColor: '#1F2937', temperature: 'warmer', category: 'daisy',
    description: 'Spooky Halloween theme',
    componentConfig: {
      headingFont: 'Oswald', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Garden', baseColor: '#F0FDF4', temperature: 'natural', category: 'daisy',
    description: 'Natural garden theme',
    componentConfig: {
      headingFont: 'Nunito', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Forest', baseColor: '#1E2A2E', temperature: 'cooler', category: 'daisy',
    description: 'Deep forest theme',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Aqua', baseColor: '#ECFEFF', temperature: 'cooler', category: 'daisy',
    description: 'Fresh aqua theme',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Open Sans',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'lg', inputRadius: 'full',
      shadow: 'md', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Luxury', baseColor: '#171717', temperature: 'cooler', category: 'daisy',
    description: 'Premium luxury theme',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'lg', lineHeight: 'loose',
      letterSpacing: 'wide',
      buttonRadius: 'md', cardRadius: 'xl', inputRadius: 'md',
      shadow: 'xl', density: 'spacious', borderWidth: '2',
    },
  },
  {
    name: 'Daisy Pastel', baseColor: '#F9F7F5', temperature: 'warmer', category: 'daisy',
    description: 'Soft pastel colors',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Nunito',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'lg', inputRadius: 'full',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Fantasy', baseColor: '#1E1A3E', temperature: 'cooler', category: 'daisy',
    description: 'Magical fantasy theme',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'xl', inputRadius: 'lg',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Noir', baseColor: '#0A0A0A', temperature: 'cooler', category: 'daisy',
    description: 'Film noir aesthetic',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'normal',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'compact', borderWidth: '0',
    },
  },
  {
    name: 'Daisy Nord', baseColor: '#242933', temperature: 'cooler', category: 'daisy',
    description: 'Nordic frost palette',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Dracula', baseColor: '#282A36', temperature: 'cooler', category: 'daisy',
    description: 'Popular Dracula scheme',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Coffee', baseColor: '#20161F', temperature: 'warmer', category: 'daisy',
    description: 'Warm coffee tones',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Lato',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },

];
