import type { Preset } from '../../../../types';

export const presets: Preset[] = [
  // ==================== SHADCN UI INSPIRED ====================
  {
    name: 'Shadcn Default', baseColor: '#09090B', temperature: 'natural', category: 'shadcn',
    description: 'The classic shadcn/ui aesthetic',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Shadcn Slate', baseColor: '#020617', temperature: 'cooler', category: 'shadcn',
    description: 'Clean slate background',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Shadcn Zinc', baseColor: '#18181B', temperature: 'natural', category: 'shadcn',
    description: 'Modern zinc gray',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Shadcn Neutral', baseColor: '#171717', temperature: 'natural', category: 'shadcn',
    description: 'Balanced neutral tones',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'none', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Shadcn Stone', baseColor: '#1C1917', temperature: 'warmer', category: 'shadcn',
    description: 'Warm stone texture',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Shadcn Rose', baseColor: '#881337', temperature: 'warmer', category: 'shadcn',
    description: 'Elegant rose accent',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Shadcn Emerald', baseColor: '#022C22', temperature: 'cooler', category: 'shadcn',
    description: 'Fresh emerald green',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Shadcn Violet', baseColor: '#2E1065', temperature: 'cooler', category: 'shadcn',
    description: 'Deep violet accent',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Shadcn Orange', baseColor: '#431407', temperature: 'warmer', category: 'shadcn',
    description: 'Warm orange tones',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Shadcn Cyan', baseColor: '#083344', temperature: 'cooler', category: 'shadcn',
    description: 'Fresh cyan accent',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Shadcn Red', baseColor: '#7F1A1A', temperature: 'warmer', category: 'shadcn',
    description: 'Bold red accent',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Shadcn Amber', baseColor: '#78350F', temperature: 'warmer', category: 'shadcn',
    description: 'Warm amber tones',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Shadcn Lime', baseColor: '#1A2E05', temperature: 'cooler', category: 'shadcn',
    description: 'Fresh lime accent',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Shadcn Teal', baseColor: '#042F2E', temperature: 'cooler', category: 'shadcn',
    description: 'Calming teal',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Shadcn Fuchsia', baseColor: '#4A044E', temperature: 'cooler', category: 'shadcn',
    description: 'Vibrant fuchsia',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Shadcn Green', baseColor: '#16A34A', temperature: 'natural', category: 'shadcn',
    description: 'Fresh green primary',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },

  // ==================== DAISY UI COMPLETE THEMES ====================
  {
    name: 'Daisy Default', baseColor: '#1E1E2F', temperature: 'natural', category: 'daisy',
    description: 'DaisyUI default theme',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Light', baseColor: '#FFFFFF', temperature: 'natural', category: 'daisy',
    description: 'Bright and airy',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Dark', baseColor: '#1F2937', temperature: 'cooler', category: 'daisy',
    description: 'Deep dark theme',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Cupcake', baseColor: '#FDF4FF', temperature: 'warmer', category: 'daisy',
    description: 'Sweet and playful',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Nunito',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'relaxed',
      letterSpacing: 'wide',
      buttonRadius: 'full', cardRadius: 'lg', inputRadius: 'full',
      shadow: 'md', density: 'spacious', borderWidth: '2',
    },
  },
  {
    name: 'Daisy Bumblebee', baseColor: '#FEF3C7', temperature: 'warmer', category: 'daisy',
    description: 'Bright yellow energy',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '2',
    },
  },
  {
    name: 'Daisy Emerald', baseColor: '#ECFDF5', temperature: 'cooler', category: 'daisy',
    description: 'Fresh green theme',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Corporate', baseColor: '#F9FAFB', temperature: 'cooler', category: 'daisy',
    description: 'Professional corporate',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: 'xl', fontSizeBody: 'sm', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'compact', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Synthwave', baseColor: '#2D1B69', temperature: 'cooler', category: 'daisy',
    description: 'Retro synthwave vibes',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'tight',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'xl', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Daisy Retro', baseColor: '#E4D5B7', temperature: 'warmer', category: 'daisy',
    description: 'Vintage retro style',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Cyberpunk', baseColor: '#0F172A', temperature: 'cooler', category: 'daisy',
    description: 'Neon cyberpunk theme',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'tight',
      buttonRadius: 'sm', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'lg', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Daisy Valentine', baseColor: '#FCE7F3', temperature: 'warmer', category: 'daisy',
    description: 'Romantic pink theme',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Nunito',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'lg', inputRadius: 'full',
      shadow: 'md', density: 'spacious', borderWidth: '2',
    },
  },
  {
    name: 'Daisy Halloween', baseColor: '#1F2937', temperature: 'warmer', category: 'daisy',
    description: 'Spooky Halloween theme',
    componentConfig: {
      headingFont: 'Oswald', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Garden', baseColor: '#F0FDF4', temperature: 'natural', category: 'daisy',
    description: 'Natural garden theme',
    componentConfig: {
      headingFont: 'Nunito', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Forest', baseColor: '#1E2A2E', temperature: 'cooler', category: 'daisy',
    description: 'Deep forest theme',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Aqua', baseColor: '#ECFEFF', temperature: 'cooler', category: 'daisy',
    description: 'Fresh aqua theme',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Open Sans',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'lg', inputRadius: 'full',
      shadow: 'md', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Luxury', baseColor: '#171717', temperature: 'cooler', category: 'daisy',
    description: 'Premium luxury theme',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'lg', lineHeight: 'loose',
      letterSpacing: 'wide',
      buttonRadius: 'md', cardRadius: 'xl', inputRadius: 'md',
      shadow: 'xl', density: 'spacious', borderWidth: '2',
    },
  },
  {
    name: 'Daisy Pastel', baseColor: '#F9F7F5', temperature: 'warmer', category: 'daisy',
    description: 'Soft pastel colors',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Nunito',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'lg', inputRadius: 'full',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Fantasy', baseColor: '#1E1A3E', temperature: 'cooler', category: 'daisy',
    description: 'Magical fantasy theme',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'xl', inputRadius: 'lg',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Noir', baseColor: '#0A0A0A', temperature: 'cooler', category: 'daisy',
    description: 'Film noir aesthetic',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'normal',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'compact', borderWidth: '0',
    },
  },
  {
    name: 'Daisy Nord', baseColor: '#242933', temperature: 'cooler', category: 'daisy',
    description: 'Nordic frost palette',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Dracula', baseColor: '#282A36', temperature: 'cooler', category: 'daisy',
    description: 'Popular Dracula scheme',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Daisy Coffee', baseColor: '#20161F', temperature: 'warmer', category: 'daisy',
    description: 'Warm coffee tones',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Lato',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },

  // ==================== MODERN CATEGORY ====================
  {
    name: 'Modern Minimal', baseColor: '#0F172A', temperature: 'cooler', category: 'modern',
    description: 'Clean and contemporary',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'tight',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Glassmorphism', baseColor: '#3B82F6', temperature: 'natural', category: 'modern',
    description: 'Frosted glass effect',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'xl', inputRadius: 'md',
      shadow: 'xl', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Neubrutalism', baseColor: '#171717', temperature: 'natural', category: 'modern',
    description: 'Bold and raw',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '800', bodyWeight: '500',
      fontSizeHeading: '4xl', fontSizeBody: 'lg', lineHeight: 'compact',
      letterSpacing: 'tight',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'compact', borderWidth: '4',
    },
  },
  {
    name: 'Rose Gold', baseColor: '#BE185D', temperature: 'warmer', category: 'modern',
    description: 'Elegant and refined',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Nordic Frost', baseColor: '#E2E8F0', temperature: 'cooler', category: 'modern',
    description: 'Scandinavian simplicity',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: 'xl', fontSizeBody: 'sm', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'spacious', borderWidth: '0',
    },
  },
  {
    name: 'Tech Noir', baseColor: '#1A1A2E', temperature: 'cooler', category: 'modern',
    description: 'Cyberpunk minimalism',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'sm', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Aurora', baseColor: '#0F2027', temperature: 'cooler', category: 'modern',
    description: 'Northern lights inspiration',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Monochrome', baseColor: '#2D2D2D', temperature: 'natural', category: 'modern',
    description: 'Black and white elegance',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'compact', borderWidth: '1',
    },
  },
  {
    name: 'Vaporwave', baseColor: '#FF71CE', temperature: 'cooler', category: 'modern',
    description: '80s vaporwave aesthetic',
    componentConfig: {
      headingFont: 'Bebas Neue', bodyFont: 'DM Sans',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'lg', lineHeight: 'compact',
      letterSpacing: 'wide',
      buttonRadius: 'sm', cardRadius: 'md', inputRadius: 'sm',
      shadow: 'xl', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Brutalism', baseColor: '#000000', temperature: 'natural', category: 'modern',
    description: 'Raw brutalist design',
    componentConfig: {
      headingFont: 'Oswald', bodyFont: 'Inter',
      headingWeight: '900', bodyWeight: '500',
      fontSizeHeading: '4xl', fontSizeBody: 'lg', lineHeight: 'compact',
      letterSpacing: 'tight',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'compact', borderWidth: '8',
    },
  },
  {
    name: 'Vercel Dark', baseColor: '#000000', temperature: 'natural', category: 'modern',
    description: 'Vercel-inspired dark UI',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'sm', lineHeight: 'normal',
      letterSpacing: 'tight',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'none', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Linear Style', baseColor: '#5E6AD2', temperature: 'cooler', category: 'modern',
    description: 'Linear-app inspired',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: 'xl', fontSizeBody: 'sm', lineHeight: 'compact',
      letterSpacing: 'tight',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'sm', density: 'compact', borderWidth: '1',
    },
  },

  // ==================== MINIMAL CATEGORY ====================
  {
    name: 'Pure Minimal', baseColor: '#111827', temperature: 'natural', category: 'minimal',
    description: 'Less is more',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: 'xl', fontSizeBody: 'sm', lineHeight: 'compact',
      letterSpacing: 'normal',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Zen White', baseColor: '#FFFFFF', temperature: 'natural', category: 'minimal',
    description: 'Peaceful simplicity',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'DM Sans',
      headingWeight: '400', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'loose',
      letterSpacing: 'wide',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'none', density: 'spacious', borderWidth: '0',
    },
  },
  {
    name: 'Calm Gray', baseColor: '#6B7280', temperature: 'natural', category: 'minimal',
    description: 'Understated elegance',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '400', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'none', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Soft Touch', baseColor: '#F3F4F6', temperature: 'warmer', category: 'minimal',
    description: 'Gentle and welcoming',
    componentConfig: {
      headingFont: 'Nunito', bodyFont: 'Inter',
      headingWeight: '400', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'lg', inputRadius: 'full',
      shadow: 'sm', density: 'spacious', borderWidth: '0',
    },
  },
  {
    name: 'Architect', baseColor: '#4A4A4A', temperature: 'natural', category: 'minimal',
    description: 'Clean architectural lines',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Whisper', baseColor: '#FAFAF9', temperature: 'warmer', category: 'minimal',
    description: 'Subtle and quiet',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '400', bodyWeight: '400',
      fontSizeHeading: 'xl', fontSizeBody: 'sm', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'none', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Bare', baseColor: '#EFEBE9', temperature: 'warmer', category: 'minimal',
    description: 'Bare essentials',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '400', bodyWeight: '400',
      fontSizeHeading: 'xl', fontSizeBody: 'sm', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'normal', borderWidth: '0',
    },
  },
  {
    name: 'Muji Inspired', baseColor: '#3C3C3C', temperature: 'natural', category: 'minimal',
    description: 'Japanese minimalism',
    componentConfig: {
      headingFont: 'Noto Sans', bodyFont: 'Noto Sans',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: 'xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'sm', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'none', density: 'spacious', borderWidth: '1',
    },
  },

  // ==================== DARK CATEGORY ====================
  {
    name: 'Dark Matter', baseColor: '#0A0A0A', temperature: 'cooler', category: 'dark',
    description: 'Deep space aesthetic',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Open Sans',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '0',
    },
  },
  {
    name: 'Cyberpunk', baseColor: '#FF00FF', temperature: 'cooler', category: 'dark',
    description: 'Neon-drenched future',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Manrope',
      headingWeight: '800', bodyWeight: '500',
      fontSizeHeading: '4xl', fontSizeBody: 'lg', lineHeight: 'compact',
      letterSpacing: 'tight',
      buttonRadius: 'sm', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'lg', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Midnight Indigo', baseColor: '#1E1B4B', temperature: 'cooler', category: 'dark',
    description: 'Deep purple night',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'xl', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Obsidian', baseColor: '#000000', temperature: 'cooler', category: 'dark',
    description: 'Pure black elegance',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '400', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'md', density: 'compact', borderWidth: '0',
    },
  },
  {
    name: 'Deep Ocean', baseColor: '#001F3F', temperature: 'cooler', category: 'dark',
    description: 'Mysterious depths',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Purple Haze', baseColor: '#2E1A47', temperature: 'cooler', category: 'dark',
    description: 'Mystical purple tones',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'xl', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Matrix', baseColor: '#003B00', temperature: 'cooler', category: 'dark',
    description: 'Digital rain aesthetic',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'normal',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'sm', density: 'compact', borderWidth: '1',
    },
  },
  {
    name: 'Void', baseColor: '#121212', temperature: 'cooler', category: 'dark',
    description: 'Minimal darkness',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '400', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'none', density: 'normal', borderWidth: '0',
    },
  },
  {
    name: 'Nightfall', baseColor: '#1A1F2E', temperature: 'cooler', category: 'dark',
    description: 'Twilight hues',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Blood Moon', baseColor: '#2D0A0A', temperature: 'warmer', category: 'dark',
    description: 'Dark red aesthetic',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Abyss', baseColor: '#0B1120', temperature: 'cooler', category: 'dark',
    description: 'Bottomless depths',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Midnight Ocean', baseColor: '#0C1445', temperature: 'cooler', category: 'dark',
    description: 'Deep ocean at night',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'xl', inputRadius: 'lg',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },

  // ==================== PLAYFUL CATEGORY ====================
  {
    name: 'Bubblegum', baseColor: '#EC4899', temperature: 'warmer', category: 'playful',
    description: 'Sweet and fun',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Nunito',
      headingWeight: '800', bodyWeight: '500',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'xl', inputRadius: 'full',
      shadow: 'sm', density: 'spacious', borderWidth: '2',
    },
  },
  {
    name: 'Pastel Dreams', baseColor: '#C4B5FD', temperature: 'cooler', category: 'playful',
    description: 'Soft and dreamy',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Nunito',
      headingWeight: '400', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'none', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Candy Crush', baseColor: '#FF6B6B', temperature: 'warmer', category: 'playful',
    description: 'Sweet treats',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Nunito',
      headingWeight: '700', bodyWeight: '500',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'xl', inputRadius: 'full',
      shadow: 'md', density: 'spacious', borderWidth: '2',
    },
  },
  {
    name: 'Neon Pop', baseColor: '#00FF87', temperature: 'cooler', category: 'playful',
    description: 'Electric energy',
    componentConfig: {
      headingFont: 'Bebas Neue', bodyFont: 'DM Sans',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'lg', lineHeight: 'compact',
      letterSpacing: 'wide',
      buttonRadius: 'sm', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'lg', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Sunset Vibes', baseColor: '#FF9A8B', temperature: 'warmer', category: 'playful',
    description: 'Warm and vibrant',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Open Sans',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Tropical', baseColor: '#FF6B6B', temperature: 'warmer', category: 'playful',
    description: 'Island paradise',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'xl', inputRadius: 'full',
      shadow: 'md', density: 'spacious', borderWidth: '2',
    },
  },
  {
    name: 'Galaxy Candy', baseColor: '#FF69B4', temperature: 'warmer', category: 'playful',
    description: 'Cosmic sweetness',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Nunito',
      headingWeight: '800', bodyWeight: '500',
      fontSizeHeading: '4xl', fontSizeBody: 'lg', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'xl', inputRadius: 'full',
      shadow: 'xl', density: 'spacious', borderWidth: '2',
    },
  },
  {
    name: 'Rainbow', baseColor: '#FF1493', temperature: 'warmer', category: 'playful',
    description: 'Colorful rainbow vibes',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Nunito',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'xl', inputRadius: 'full',
      shadow: 'lg', density: 'spacious', borderWidth: '2',
    },
  },
  {
    name: 'Cotton Candy', baseColor: '#A6C1FF', temperature: 'cooler', category: 'playful',
    description: 'Soft and fluffy',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Nunito',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'lg', inputRadius: 'full',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Toybox', baseColor: '#FFD700', temperature: 'warmer', category: 'playful',
    description: 'Bright and energetic',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Nunito',
      headingWeight: '700', bodyWeight: '500',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'relaxed',
      letterSpacing: 'wide',
      buttonRadius: 'full', cardRadius: '2xl', inputRadius: 'full',
      shadow: 'lg', density: 'spacious', borderWidth: '4',
    },
  },

  // ==================== PROFESSIONAL CATEGORY ====================
  {
    name: 'Corporate Blue', baseColor: '#2563EB', temperature: 'cooler', category: 'professional',
    description: 'Trustworthy and clean',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Executive', baseColor: '#0F172A', temperature: 'natural', category: 'professional',
    description: 'Sophisticated authority',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'md', density: 'compact', borderWidth: '1',
    },
  },
  {
    name: 'SaaS Modern', baseColor: '#6366F1', temperature: 'cooler', category: 'professional',
    description: 'Tech-forward',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Finance', baseColor: '#047857', temperature: 'cooler', category: 'professional',
    description: 'Stable and reliable',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: 'xl', fontSizeBody: 'sm', lineHeight: 'compact',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'compact', borderWidth: '1',
    },
  },
  {
    name: 'Consultant', baseColor: '#5B21B6', temperature: 'cooler', category: 'professional',
    description: 'Wise and strategic',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Law Firm', baseColor: '#1E293B', temperature: 'natural', category: 'professional',
    description: 'Authoritative tradition',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Tech Startup', baseColor: '#06B6D4', temperature: 'cooler', category: 'professional',
    description: 'Innovative and fresh',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Healthcare', baseColor: '#0891B2', temperature: 'cooler', category: 'professional',
    description: 'Calm and caring',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'lg', inputRadius: 'full',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Education', baseColor: '#EAB308', temperature: 'warmer', category: 'professional',
    description: 'Warm and approachable',
    componentConfig: {
      headingFont: 'Nunito', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Agency', baseColor: '#EC4899', temperature: 'warmer', category: 'professional',
    description: 'Creative agency style',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Enterprise Gray', baseColor: '#374151', temperature: 'natural', category: 'professional',
    description: 'Serious business UI',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: 'xl', fontSizeBody: 'sm', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'sm', cardRadius: 'md', inputRadius: 'sm',
      shadow: 'sm', density: 'compact', borderWidth: '1',
    },
  },
  {
    name: 'Fintech Pro', baseColor: '#6366F1', temperature: 'cooler', category: 'professional',
    description: 'Modern fintech look',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'sm', lineHeight: 'normal',
      letterSpacing: 'tight',
      buttonRadius: 'lg', cardRadius: 'xl', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },

  // ==================== NATURE CATEGORY ====================
  {
    name: 'Forest', baseColor: '#059669', temperature: 'natural', category: 'nature',
    description: 'Woodland retreat',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Ocean Breeze', baseColor: '#0891B2', temperature: 'cooler', category: 'nature',
    description: 'Coastal calm',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Open Sans',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'lg', inputRadius: 'full',
      shadow: 'md', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Sage Garden', baseColor: '#84A98C', temperature: 'natural', category: 'nature',
    description: 'Herbal serenity',
    componentConfig: {
      headingFont: 'Nunito', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Desert Rose', baseColor: '#E6B17E', temperature: 'warmer', category: 'nature',
    description: 'Warm sands',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Open Sans',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Moss', baseColor: '#2C5F2D', temperature: 'natural', category: 'nature',
    description: 'Lush green',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Lavender Field', baseColor: '#967AA1', temperature: 'cooler', category: 'nature',
    description: 'Soothing purple',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Nunito',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'lg', inputRadius: 'full',
      shadow: 'md', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Sunflower', baseColor: '#F4D03F', temperature: 'warmer', category: 'nature',
    description: 'Bright and cheerful',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'lg', density: 'normal', borderWidth: '2',
    },
  },
  {
    name: 'Meadow', baseColor: '#7CB518', temperature: 'cooler', category: 'nature',
    description: 'Fresh spring meadow',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Autumn', baseColor: '#D97706', temperature: 'warmer', category: 'nature',
    description: 'Warm autumn colors',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Desert Sand', baseColor: '#C2956B', temperature: 'warmer', category: 'nature',
    description: 'Warm desert tones',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Open Sans',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },

  // ==================== VINTAGE CATEGORY ====================
  {
    name: 'Vintage Paper', baseColor: '#D4A373', temperature: 'warmer', category: 'vintage',
    description: 'Aged parchment',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Sunset', baseColor: '#EA580C', temperature: 'warmer', category: 'vintage',
    description: 'Golden hour glow',
    componentConfig: {
      headingFont: 'Bebas Neue', bodyFont: 'DM Sans',
      headingWeight: '800', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'lg', lineHeight: 'compact',
      letterSpacing: 'wide',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Retro Wave', baseColor: '#FF6B35', temperature: 'warmer', category: 'vintage',
    description: '80s aesthetic',
    componentConfig: {
      headingFont: 'Oswald', bodyFont: 'DM Sans',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'compact',
      letterSpacing: 'tight',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'md', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Sepia', baseColor: '#C06C4F', temperature: 'warmer', category: 'vintage',
    description: 'Old photograph',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Art Deco', baseColor: '#D4AF37', temperature: 'warmer', category: 'vintage',
    description: 'Gatsby era',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Open Sans',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'widest',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'lg', density: 'compact', borderWidth: '1',
    },
  },
  {
    name: 'Mid-Century', baseColor: '#E07A5F', temperature: 'warmer', category: 'vintage',
    description: '1950s modern',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Victorian', baseColor: '#8B5A2B', temperature: 'warmer', category: 'vintage',
    description: 'Classic Victorian style',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },

  // ==================== FUTURISTIC CATEGORY ====================
  {
    name: 'Hologram', baseColor: '#00F5FF', temperature: 'cooler', category: 'futuristic',
    description: 'Holographic interface',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'wider',
      buttonRadius: 'sm', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'xl', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Neo Tokyo', baseColor: '#FF0055', temperature: 'cooler', category: 'futuristic',
    description: 'Cyberpunk city',
    componentConfig: {
      headingFont: 'Oswald', bodyFont: 'Manrope',
      headingWeight: '800', bodyWeight: '500',
      fontSizeHeading: '4xl', fontSizeBody: 'lg', lineHeight: 'compact',
      letterSpacing: 'tight',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'lg', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Digital', baseColor: '#00F260', temperature: 'cooler', category: 'futuristic',
    description: 'Digital interface',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'lg', density: 'compact', borderWidth: '1',
    },
  },
  {
    name: 'Cyberspace', baseColor: '#4A00E0', temperature: 'cooler', category: 'futuristic',
    description: 'Digital cyberspace',
    componentConfig: {
      headingFont: 'Roboto Mono', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'normal',
      buttonRadius: 'sm', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'xl', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Quantum', baseColor: '#7C3AED', temperature: 'cooler', category: 'futuristic',
    description: 'Quantum computing aesthetic',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'xl', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'AI Dashboard', baseColor: '#7C3AED', temperature: 'cooler', category: 'futuristic',
    description: 'AI-powered interface',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'sm', lineHeight: 'normal',
      letterSpacing: 'tight',
      buttonRadius: 'lg', cardRadius: 'xl', inputRadius: 'lg',
      shadow: 'lg', density: 'normal', borderWidth: '1',
    },
  },

  // ==================== LUXURY CATEGORY ====================
  {
    name: 'Gold Leaf', baseColor: '#B8860B', temperature: 'warmer', category: 'luxury',
    description: 'Opulent elegance',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'lg', lineHeight: 'loose',
      letterSpacing: 'wide',
      buttonRadius: 'md', cardRadius: 'xl', inputRadius: 'md',
      shadow: 'xl', density: 'spacious', borderWidth: '2',
    },
  },
  {
    name: 'Platinum', baseColor: '#E5E4E2', temperature: 'cooler', category: 'luxury',
    description: 'Premium metallic',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '400', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'lg', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Royal', baseColor: '#6C3483', temperature: 'cooler', category: 'luxury',
    description: 'Regal purple',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'xl', inputRadius: 'md',
      shadow: 'xl', density: 'normal', borderWidth: '2',
    },
  },
  {
    name: 'Diamond', baseColor: '#F8F9FA', temperature: 'cooler', category: 'luxury',
    description: 'Diamond brilliance',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '400', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'xl', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Sapphire', baseColor: '#0F52BA', temperature: 'cooler', category: 'luxury',
    description: 'Deep sapphire blue',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'lg', density: 'normal', borderWidth: '2',
    },
  },
  {
    name: 'Emerald', baseColor: '#50C878', temperature: 'cooler', category: 'luxury',
    description: 'Luxurious emerald green',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'xl', inputRadius: 'lg',
      shadow: 'lg', density: 'spacious', borderWidth: '2',
    },
  },
  {
    name: 'Noir Luxury', baseColor: '#1A1A2E', temperature: 'cooler', category: 'luxury',
    description: 'Dark luxury fashion',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Open Sans',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'wider',
      buttonRadius: 'none', cardRadius: 'sm', inputRadius: 'none',
      shadow: 'none', density: 'spacious', borderWidth: '1',
    },
  },

  // ==================== ARTISTIC CATEGORY ====================
  {
    name: 'Watercolor', baseColor: '#A6C1E0', temperature: 'cooler', category: 'artistic',
    description: 'Soft brush strokes',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Nunito',
      headingWeight: '400', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'loose',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'xl', inputRadius: 'full',
      shadow: 'md', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Sketch', baseColor: '#2C3E50', temperature: 'natural', category: 'artistic',
    description: 'Hand-drawn style',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Bauhaus', baseColor: '#E31B23', temperature: 'warmer', category: 'artistic',
    description: 'Bold primary colors',
    componentConfig: {
      headingFont: 'Bebas Neue', bodyFont: 'DM Sans',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'compact',
      letterSpacing: 'wide',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'md', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Pop Art', baseColor: '#FF4D4D', temperature: 'warmer', category: 'artistic',
    description: 'Warhol-inspired pop art',
    componentConfig: {
      headingFont: 'Bebas Neue', bodyFont: 'DM Sans',
      headingWeight: '800', bodyWeight: '500',
      fontSizeHeading: '4xl', fontSizeBody: 'lg', lineHeight: 'compact',
      letterSpacing: 'wide',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'lg', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Impressionism', baseColor: '#D4AF37', temperature: 'warmer', category: 'artistic',
    description: 'Soft impressionist style',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'xl', inputRadius: 'full',
      shadow: 'md', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Abstract', baseColor: '#FF6B6B', temperature: 'warmer', category: 'artistic',
    description: 'Bold abstract shapes',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Open Sans',
      headingWeight: '800', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'tight',
      buttonRadius: 'lg', cardRadius: '2xl', inputRadius: 'lg',
      shadow: 'lg', density: 'normal', borderWidth: '2',
    },
  },

  // ==================== WARM CATEGORY ====================
  {
    name: 'Sunset Glow', baseColor: '#F97316', temperature: 'warmer', category: 'warm',
    description: 'Golden hour warmth',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Open Sans',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Terracotta', baseColor: '#C85A37', temperature: 'warmer', category: 'warm',
    description: 'Earthy clay tones',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Open Sans',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },

  // ==================== COOL CATEGORY ====================
  {
    name: 'Arctic Frost', baseColor: '#38BDF8', temperature: 'cooler', category: 'cool',
    description: 'Icy blue clarity',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Lavender Haze', baseColor: '#A78BFA', temperature: 'cooler', category: 'cool',
    description: 'Soft purple calm',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Open Sans',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'xl', inputRadius: 'lg',
      shadow: 'md', density: 'spacious', borderWidth: '1',
    },
  },

  // ==================== MONOCHROME CATEGORY ====================
  {
    name: 'Ink & Paper', baseColor: '#000000', temperature: 'natural', category: 'monochrome',
    description: 'Pure black & white',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'DM Sans',
      headingWeight: '400', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'none', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'none', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Silver Chrome', baseColor: '#71717A', temperature: 'cooler', category: 'monochrome',
    description: 'Metallic monochrome',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'tight',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },

  // ==================== EDITORIAL CATEGORY ====================
  {
    name: 'Editorial Black', baseColor: '#0A0A0A', temperature: 'natural', category: 'editorial',
    description: 'Magazine-style editorial',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '5xl', fontSizeBody: 'base', lineHeight: 'loose',
      letterSpacing: 'tight',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Broadsheet', baseColor: '#F5F0E8', temperature: 'warmer', category: 'editorial',
    description: 'Classic newspaper layout',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Lato',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Magazine Glam', baseColor: '#FF2D55', temperature: 'warmer', category: 'editorial',
    description: 'High-fashion magazine',
    componentConfig: {
      headingFont: 'Oswald', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '5xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'widest',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'sm',
      shadow: 'none', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Longform', baseColor: '#1A1A1A', temperature: 'natural', category: 'editorial',
    description: 'Long-form content reading',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Lato',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'loose',
      letterSpacing: 'normal',
      buttonRadius: 'sm', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'none', density: 'spacious', borderWidth: '0',
    },
  },
  {
    name: 'Substack', baseColor: '#FF6719', temperature: 'warmer', category: 'editorial',
    description: 'Newsletter-first design',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'lg', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'none', cardRadius: 'sm', inputRadius: 'none',
      shadow: 'none', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Typographic', baseColor: '#212121', temperature: 'natural', category: 'editorial',
    description: 'Typography-forward design',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'DM Sans',
      headingWeight: '800', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'tighter',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'compact', borderWidth: '2',
    },
  },

  // ==================== BRUTALIST CATEGORY ====================
  {
    name: 'Raw Concrete', baseColor: '#808080', temperature: 'natural', category: 'brutalist',
    description: 'Concrete brutalism',
    componentConfig: {
      headingFont: 'Oswald', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'tight',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'compact', borderWidth: '4',
    },
  },
  {
    name: 'Anti-Design', baseColor: '#FFD700', temperature: 'warmer', category: 'brutalist',
    description: 'Deliberately ugly is beautiful',
    componentConfig: {
      headingFont: 'Oswald', bodyFont: 'Inter',
      headingWeight: '900', bodyWeight: '700',
      fontSizeHeading: '5xl', fontSizeBody: 'lg', lineHeight: 'compact',
      letterSpacing: 'widest',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'compact', borderWidth: '8',
    },
  },
  {
    name: 'Swiss Grid', baseColor: '#E8E8E8', temperature: 'natural', category: 'brutalist',
    description: 'Swiss international style',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '800', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'tighter',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Grunge', baseColor: '#3D2B1F', temperature: 'warmer', category: 'brutalist',
    description: 'Raw grunge aesthetic',
    componentConfig: {
      headingFont: 'Oswald', bodyFont: 'DM Sans',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'tight',
      buttonRadius: 'none', cardRadius: 'sm', inputRadius: 'none',
      shadow: 'none', density: 'compact', borderWidth: '4',
    },
  },

  // ==================== RETRO CATEGORY ====================
  {
    name: 'DOS Terminal', baseColor: '#00FF00', temperature: 'cooler', category: 'retro',
    description: 'Green phosphor monitor',
    componentConfig: {
      headingFont: 'Roboto Mono', bodyFont: 'Roboto Mono',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'wider',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'compact', borderWidth: '1',
    },
  },
  {
    name: 'Tape Deck', baseColor: '#1A1A1A', temperature: 'warmer', category: 'retro',
    description: 'Mixtape era design',
    componentConfig: {
      headingFont: 'Oswald', bodyFont: 'Lato',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'wide',
      buttonRadius: 'sm', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'md', density: 'normal', borderWidth: '2',
    },
  },
  {
    name: 'Neon Sign', baseColor: '#FF1493', temperature: 'cooler', category: 'retro',
    description: 'Glowing neon diner sign',
    componentConfig: {
      headingFont: 'Bebas Neue', bodyFont: 'DM Sans',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'wide',
      buttonRadius: 'sm', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'xl', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Kodak Film', baseColor: '#F4C542', temperature: 'warmer', category: 'retro',
    description: 'Golden film grain',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Lato',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'sm', cardRadius: 'md', inputRadius: 'sm',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Typewriter', baseColor: '#F5F0E8', temperature: 'warmer', category: 'retro',
    description: 'Classic typewriter feel',
    componentConfig: {
      headingFont: 'Roboto Mono', bodyFont: 'Roboto Mono',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'loose',
      letterSpacing: 'wider',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'none', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Polaroid', baseColor: '#FFF9F0', temperature: 'warmer', category: 'retro',
    description: 'Instant camera nostalgia',
    componentConfig: {
      headingFont: 'Nunito', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: 'xl', fontSizeBody: 'sm', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'sm', cardRadius: 'none', inputRadius: 'sm',
      shadow: 'xl', density: 'spacious', borderWidth: '8',
    },
  },

  // ==================== PASTEL CATEGORY ====================
  {
    name: 'Sakura', baseColor: '#FFB7C5', temperature: 'warmer', category: 'pastel',
    description: 'Cherry blossom softness',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Nunito',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'xl', inputRadius: 'full',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Mint Breeze', baseColor: '#B2EBD6', temperature: 'cooler', category: 'pastel',
    description: 'Fresh minty pastels',
    componentConfig: {
      headingFont: 'Nunito', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'lg', inputRadius: 'full',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Peach Cream', baseColor: '#FFCBA4', temperature: 'warmer', category: 'pastel',
    description: 'Soft creamy peach',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Nunito',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'xl', inputRadius: 'full',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Baby Blue', baseColor: '#BEDCF0', temperature: 'cooler', category: 'pastel',
    description: 'Soothing sky pastels',
    componentConfig: {
      headingFont: 'Nunito', bodyFont: 'Open Sans',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'lg', inputRadius: 'full',
      shadow: 'none', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Lilac Dream', baseColor: '#DEC0F1', temperature: 'cooler', category: 'pastel',
    description: 'Dreamy lilac tones',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Nunito',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'xl', inputRadius: 'full',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Butter Yellow', baseColor: '#FFF3B0', temperature: 'warmer', category: 'pastel',
    description: 'Warm buttery pastels',
    componentConfig: {
      headingFont: 'Nunito', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'lg', inputRadius: 'full',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },

  // ==================== NEON CATEGORY ====================
  {
    name: 'Neon Acid', baseColor: '#39FF14', temperature: 'cooler', category: 'neon',
    description: 'Extreme neon acid green',
    componentConfig: {
      headingFont: 'Bebas Neue', bodyFont: 'Manrope',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'lg', lineHeight: 'compact',
      letterSpacing: 'wide',
      buttonRadius: 'sm', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'xl', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Cyber Pink', baseColor: '#FF007F', temperature: 'warmer', category: 'neon',
    description: 'Bright neon pink',
    componentConfig: {
      headingFont: 'Bebas Neue', bodyFont: 'DM Sans',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'wide',
      buttonRadius: 'sm', cardRadius: 'md', inputRadius: 'sm',
      shadow: 'xl', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Electric Blue', baseColor: '#007BFF', temperature: 'cooler', category: 'neon',
    description: 'Blazing electric blue',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '800', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'tight',
      buttonRadius: 'sm', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'xl', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'Neon Orange', baseColor: '#FF6200', temperature: 'warmer', category: 'neon',
    description: 'High-voltage orange',
    componentConfig: {
      headingFont: 'Oswald', bodyFont: 'DM Sans',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'lg', lineHeight: 'compact',
      letterSpacing: 'normal',
      buttonRadius: 'none', cardRadius: 'sm', inputRadius: 'none',
      shadow: 'lg', density: 'compact', borderWidth: '2',
    },
  },
  {
    name: 'UV Purple', baseColor: '#7B00D4', temperature: 'cooler', category: 'neon',
    description: 'Ultraviolet glow',
    componentConfig: {
      headingFont: 'Bebas Neue', bodyFont: 'Manrope',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '4xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'wide',
      buttonRadius: 'sm', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'xl', density: 'compact', borderWidth: '2',
    },
  },

  // ==================== MORE WARM THEMES ====================
  {
    name: 'Amber Glow', baseColor: '#F59E0B', temperature: 'warmer', category: 'warm',
    description: 'Warm amber light',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Spice Route', baseColor: '#C05621', temperature: 'warmer', category: 'warm',
    description: 'Rustic spice palette',
    componentConfig: {
      headingFont: 'Oswald', bodyFont: 'Open Sans',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Warm Ivory', baseColor: '#FFFBEB', temperature: 'warmer', category: 'warm',
    description: 'Soft ivory warmth',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'loose',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'sm', density: 'spacious', borderWidth: '0',
    },
  },
  {
    name: 'Copper', baseColor: '#B87333', temperature: 'warmer', category: 'warm',
    description: 'Rich copper tones',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '2',
    },
  },
  {
    name: 'Sandstone', baseColor: '#D4B896', temperature: 'warmer', category: 'warm',
    description: 'Natural sandy warmth',
    componentConfig: {
      headingFont: 'Nunito', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: 'xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },

  // ==================== MORE COOL THEMES ====================
  {
    name: 'Glacier', baseColor: '#B0D4E3', temperature: 'cooler', category: 'cool',
    description: 'Cold glacier blue',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'xl', inputRadius: 'lg',
      shadow: 'sm', density: 'spacious', borderWidth: '0',
    },
  },
  {
    name: 'Steel Blue', baseColor: '#4682B4', temperature: 'cooler', category: 'cool',
    description: 'Industrial steel',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Icy Mint', baseColor: '#C2F0E8', temperature: 'cooler', category: 'cool',
    description: 'Cool fresh mint',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'xl', inputRadius: 'full',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Teal Ocean', baseColor: '#008080', temperature: 'cooler', category: 'cool',
    description: 'Deep teal waters',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Open Sans',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },

  // ==================== MORE MONOCHROME THEMES ====================
  {
    name: 'Charcoal', baseColor: '#36454F', temperature: 'natural', category: 'monochrome',
    description: 'Warm charcoal tones',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Graphite', baseColor: '#5C5C5C', temperature: 'natural', category: 'monochrome',
    description: 'Smooth graphite grey',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '400', bodyWeight: '400',
      fontSizeHeading: 'xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'sm', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'sm', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Ash Gray', baseColor: '#B2BEB5', temperature: 'cooler', category: 'monochrome',
    description: 'Muted ash tones',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '400', bodyWeight: '400',
      fontSizeHeading: 'xl', fontSizeBody: 'sm', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'none', density: 'spacious', borderWidth: '0',
    },
  },

  // ==================== APP-INSPIRED THEMES ====================
  {
    name: 'Notion Style', baseColor: '#191919', temperature: 'natural', category: 'minimal',
    description: 'Notion-inspired clean UI',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'sm', cardRadius: 'sm', inputRadius: 'sm',
      shadow: 'none', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'GitHub Dark', baseColor: '#0D1117', temperature: 'cooler', category: 'dark',
    description: 'GitHub-inspired dark mode',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'sm', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'none', density: 'compact', borderWidth: '1',
    },
  },
  {
    name: 'Stripe UI', baseColor: '#635BFF', temperature: 'cooler', category: 'professional',
    description: 'Stripe-inspired modern UI',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'tight',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Apple HIG', baseColor: '#007AFF', temperature: 'cooler', category: 'modern',
    description: 'Apple Human Interface style',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'tight',
      buttonRadius: 'full', cardRadius: 'xl', inputRadius: 'xl',
      shadow: 'sm', density: 'spacious', borderWidth: '0',
    },
  },
  {
    name: 'Material You', baseColor: '#6750A4', temperature: 'cooler', category: 'modern',
    description: 'Google Material Design 3',
    componentConfig: {
      headingFont: 'Nunito', bodyFont: 'Nunito',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'xl', inputRadius: 'full',
      shadow: 'md', density: 'normal', borderWidth: '0',
    },
  },
  {
    name: 'Fluent Design', baseColor: '#0078D4', temperature: 'cooler', category: 'modern',
    description: 'Microsoft Fluent UI style',
    componentConfig: {
      headingFont: 'Inter', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'normal',
      letterSpacing: 'normal',
      buttonRadius: 'sm', cardRadius: 'md', inputRadius: 'sm',
      shadow: 'none', density: 'normal', borderWidth: '0',
    },
  },

  // ==================== MORE NATURE THEMES ====================
  {
    name: 'Rainforest', baseColor: '#1A4731', temperature: 'natural', category: 'nature',
    description: 'Dense tropical jungle',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'lg', cardRadius: 'lg', inputRadius: 'lg',
      shadow: 'md', density: 'normal', borderWidth: '1',
    },
  },
  {
    name: 'Volcanic', baseColor: '#7F1D1D', temperature: 'warmer', category: 'nature',
    description: 'Molten lava intensity',
    componentConfig: {
      headingFont: 'Oswald', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'md', inputRadius: 'md',
      shadow: 'lg', density: 'compact', borderWidth: '1',
    },
  },
  {
    name: 'Coral Reef', baseColor: '#FF7F7F', temperature: 'warmer', category: 'nature',
    description: 'Vibrant coral underwater',
    componentConfig: {
      headingFont: 'Poppins', bodyFont: 'Open Sans',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'xl', inputRadius: 'full',
      shadow: 'md', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Northern Pines', baseColor: '#2D4A22', temperature: 'natural', category: 'nature',
    description: 'Pine forest tranquility',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: 'xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'sm', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Sky High', baseColor: '#87CEEB', temperature: 'cooler', category: 'nature',
    description: 'Open blue sky',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Open Sans',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'normal',
      buttonRadius: 'full', cardRadius: 'xl', inputRadius: 'full',
      shadow: 'sm', density: 'spacious', borderWidth: '0',
    },
  },

  // ==================== MORE FUTURISTIC THEMES ====================
  {
    name: 'Space Station', baseColor: '#1A1A2E', temperature: 'cooler', category: 'futuristic',
    description: 'Orbital station UI',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'sm', lineHeight: 'compact',
      letterSpacing: 'wider',
      buttonRadius: 'sm', cardRadius: 'md', inputRadius: 'sm',
      shadow: 'lg', density: 'compact', borderWidth: '1',
    },
  },
  {
    name: 'Bionic', baseColor: '#10B981', temperature: 'cooler', category: 'futuristic',
    description: 'Biomechanical interface',
    componentConfig: {
      headingFont: 'DM Sans', bodyFont: 'Roboto Mono',
      headingWeight: '700', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'sm', lineHeight: 'compact',
      letterSpacing: 'normal',
      buttonRadius: 'sm', cardRadius: 'md', inputRadius: 'sm',
      shadow: 'xl', density: 'compact', borderWidth: '1',
    },
  },
  {
    name: 'Plasma', baseColor: '#9C27B0', temperature: 'cooler', category: 'futuristic',
    description: 'High-energy plasma UI',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Inter',
      headingWeight: '800', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'compact',
      letterSpacing: 'tight',
      buttonRadius: 'sm', cardRadius: 'md', inputRadius: 'sm',
      shadow: 'xl', density: 'compact', borderWidth: '2',
    },
  },

  // ==================== MORE LUXURY THEMES ====================
  {
    name: 'Black Diamond', baseColor: '#0A0A0A', temperature: 'natural', category: 'luxury',
    description: 'Ultimate dark luxury',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '700', bodyWeight: '300',
      fontSizeHeading: '4xl', fontSizeBody: 'base', lineHeight: 'loose',
      letterSpacing: 'widest',
      buttonRadius: 'none', cardRadius: 'none', inputRadius: 'none',
      shadow: 'xl', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Rose Quartz', baseColor: '#B76E79', temperature: 'warmer', category: 'luxury',
    description: 'Feminine luxury gemstone',
    componentConfig: {
      headingFont: 'Playfair Display', bodyFont: 'Inter',
      headingWeight: '500', bodyWeight: '400',
      fontSizeHeading: '3xl', fontSizeBody: 'base', lineHeight: 'loose',
      letterSpacing: 'wide',
      buttonRadius: 'full', cardRadius: 'xl', inputRadius: 'full',
      shadow: 'lg', density: 'spacious', borderWidth: '1',
    },
  },
  {
    name: 'Onyx', baseColor: '#3D3635', temperature: 'natural', category: 'luxury',
    description: 'Deep onyx stone',
    componentConfig: {
      headingFont: 'Manrope', bodyFont: 'Open Sans',
      headingWeight: '600', bodyWeight: '400',
      fontSizeHeading: '2xl', fontSizeBody: 'base', lineHeight: 'relaxed',
      letterSpacing: 'wide',
      buttonRadius: 'md', cardRadius: 'lg', inputRadius: 'md',
      shadow: 'xl', density: 'spacious', borderWidth: '1',
    },
  },
];